[features]
seeds = false
skip-lint = false

[programs.localnet]
coin_flip_game = "CoinF1ipGameProgram11111111111111111111111"

[programs.mainnet]
coin_flip_game = "CoinF1ipGameProgram11111111111111111111111"
c_protocol = "CProtoco1WorkChain11111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"